plugins {
    id 'org.quiltmc.loom' version '1.2.+'
    id 'maven-publish'
}

base.archivesName = rootProject.archives_base_name + '-quilt'

dependencies {
    minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "org.quiltmc:quilt-loader:${rootProject.quilt_loader_version}"
    modImplementation "org.quiltmc.quilted-fabric-api:quilted-fabric-api:${rootProject.quilt_fabric_api_version}"
}

sourceSets.main.java.srcDir(rootProject.file('common/src/main/java'))
sourceSets.main.java.srcDir(rootProject.file('fabric_like/src/main/java'))
sourceSets.main.resources.srcDir(rootProject.file('common/src/main/resources'))

processResources {
    inputs.property 'version', project.version
    inputs.property 'group', project.group
    inputs.property 'id', rootProject.archives_base_name
    filesMatching('quilt.mod.json') {
        expand version: project.version, group: project.group, id: rootProject.archives_base_name
    }
}

jar {
    from(rootProject.file('LICENSE'))
}

sourcesJar {
    from(rootProject.file('LICENSE'))
}

publishing {
    publications {
        mavenQuilt(MavenPublication) {
            from components.java
        }
    }
}
